---
- name: Main Playbook
  hosts: localhost
  gather_facts: true  # Ensure platform facts are gathered
  become: true        # Required for sudo on Ubuntu

  tasks:
    - name: Include macOS tasks
      include_tasks: tasks/macos-packages.yml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Include Ubuntu tasks
      include_tasks: tasks/ubuntu-packages.yml
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Oh My Zsh
      include_tasks: tasks/oh-my-zsh.yml

    # Switch main shell to zsh
    - name: Change default shell to zsh
      ansible.builtin.shell: chsh -s $(which zsh) "{{ ansible_user_id }}"

- import_playbook: tasks/install-python.yml
#- import_playbook: tasks/setup-ssh.yml
#- import_playbook: tasks/clone-lilydevtools.yml