---

- name: Debug home directory
  ansible.builtin.debug:
    msg: "Home directory is {{ ansible_env.HOME }}"

- name: Append conda activate to .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.lilyrc"
    line: 'conda activate PyEnv3.9'
    create: yes