---

- name: Tasks running as non-sudo user
  hosts: localhost
  become: true
  become_user: lily  # Runs as non sudo user

  tasks:
    - name: Verify $HOME environment variable
      ansible.builtin.shell: echo $HOME
      
      register: home_output

    - name: Display the value of $HOME
      ansible.builtin.debug:
        var: home_output.stdout

    - name: Debug home directory
      become: true
      become_user: lily
      ansible.builtin.debug:
        msg: "Home directory is {{ ansible_env.HOME }}"

    - name: Append conda activate to .zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'conda activate PyEnv3.9'
        create: yes