---
- name: Main Playbook
  hosts: localhost
  gather_facts: true  # Ensure platform facts are gathered
  become: true        # Required for sudo on Ubuntu

  tasks:
    - name: Ensure ~/.zshrc is properly initialized
      ansible.builtin.shell: |
        echo '\nconda activate PyEnv3.9' >> /home/lily/.zshrc