---
- name: Main Playbook
  hosts: localhost
  gather_facts: true  # Ensure platform facts are gathered
  become: true        # Required for sudo on Ubuntu

  tasks:
    - name: include non sudo
      include_tasks: nonsudo.yml
        