
---
- name: Setup Python Environment
  hosts: localhost
  gather_facts: true

  tasks:
    # Install Miniconda
    - name: Download Miniconda installer
      ansible.builtin.get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/Miniconda3-latest-Linux-x86_64.sh
        mode: '0755'

    - name: Run Miniconda installer
      ansible.builtin.shell: bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda

    - name: Initialize conda
      ansible.builtin.shell: $HOME/miniconda/bin/conda init

    - name: Create Python 3.9 envrioment
      ansible.builtin.shell: $HOME/miniconda/bin/conda create --name PyEnv3.9 python=3.9 -y

    - name: Activate Python 3.9 environment
      ansible.builtin.shell: source $HOME/.bashrc && conda activate PyEnv3.9